### ISSUE TITLE
Husky precommit error when using Gitpod

### ISSUE THREAD

**Issue by HonkingGoose** [Belco90/octochangelog#465]
### Describe the bug

Husky precommit fails with Gitpod whenever I'm making a commit.

### Give the steps to reproduce

1. Open repository in Gitpod
2. Make sure the initial Yarn run completes succesfully
3. Edit a file, and save changes in VSCode
4. Create a new commit with `git commit -m "message"
5. Husky runs and fails to complete successfully:

```bash
yarn run v1.22.15
$ /workspace/octoclairvoyant/node_modules/.bin/lint-staged
✔ Preparing...
✔ Running tasks...
✔ Applying modifications...
✔ Cleaning up...
Done in 1.73s.
.husky/pre-commit: 12: Syntax error: "(" unexpected (expecting "then")
husky - pre-commit hook exited with code 2 (error)
```

### What browsers are you seeing the problem on?

Bug is not about browser

### Have you thought of a possible solution?

No

### Do you want to help fix the bug?

Yes

### Is there anything else we need to know?

I don't know what's causing this problem, it might be something specific to our Gitpod setup, like a incorrect version of node/yarn/whatever. It might be a limitation of Gitpod that it does not work with husky correctly.

Maybe you can try to debug what's going wrong? I assume it works on your local workstation just fine?

**Comment by Belco90** [comment]
No idea about this to be honest, and I'm afraid I don't have time to take a look at it. I'd create an issue in [gitpod repo](https://github.com/gitpod-io/gitpod) instead so they can take a look at it.
